name: macro_proposal
publish_to: none
environment:
  sdk: ">=2.17.0-0 <3.0.0"
dev_dependencies:
  args: ^2.3.0
  dart_style: ^2.2.1
  _fe_analyzer_shared: any
  frontend_server: any

# Override to the latest version of the in progress api.
dependency_overrides:
  _fe_analyzer_shared:
    # git:
    #   url: https://github.com/dart-lang/sdk.git
    #   path: pkg/_fe_analyzer_shared
    path: ../../../../dart-lang-sdk/sdk/pkg/_fe_analyzer_shared
  analyzer:
    # git:
    #   url: https://github.com/dart-lang/sdk.git
    #   path: pkg/analyzer
    path: ../../../../dart-lang-sdk/sdk/pkg/analyzer
  build_integration:
    # git:
    #   url: https://github.com/dart-lang/sdk.git
    #   path: pkg/build_integration
    path: ../../../../dart-lang-sdk/sdk/pkg/build_integration
  front_end:
    # git:
    #   url: https://github.com/dart-lang/sdk.git
    #   path: pkg/front_end
    path: ../../../../dart-lang-sdk/sdk/pkg/front_end
  frontend_server:
    # git:
    #   url: https://github.com/dart-lang/sdk.git
    #   path: pkg/frontend_server
    path: ../../../../dart-lang-sdk/sdk/pkg/frontend_server
  kernel:
    # git:
    #   url: https://github.com/dart-lang/sdk.git
    #   path: pkg/kernel
    path: ../../../../dart-lang-sdk/sdk/pkg/kernel
